/**:
  ros__parameters:
    # Map settings
    resolution: 0.05          # meters per cell
    size_x: 200               # number of cells (10 m)
    size_y: 200               # number of cells (10 m)
    theta_bins: 36            # number of discrete orientations
    origin_x: -5.0            # map origin in meters
    origin_y: -5.0

    # Motion model
    trans_sigma: 0.05
    rot_sigma: 0.05
    trans_rot_sigma: 0.02

    # Sensor model
    z_hit: 0.9
    z_rand: 0.1
    sigma_hit: 0.2
    max_range: 3.5            # match your lidar

    # Update parameters
    skip_beams: 3             # use every Nth beam for speed
    downsample_theta: 2       # only update every Nth theta bin

    # Publish rate
    publish_rate_hz: 8

    # Frames
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_footprint"

    # Use simulated time
    use_sim_time: true
